spring.application.name=JornadaPet

# H2 — banco em memória (mesmo padrão do professor)
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always