spring.application.name=JornadaPet


spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jwt.secret=jornadapet-secret-key-muito-segura-2026
jwt.expiration=86400000