package br.com.fiap.VetSync.security;

public enum PermissaoClinica {
    PERFIL_VER, PERFIL_EDITAR,
    SERVICOS_VER, SERVICOS_EDITAR,
    AGENDA_VER, AGENDA_CRIAR, AGENDA_REAGENDAR, AGENDA_CANCELAR,
    MENSAGENS_VER, MENSAGENS_INICIAR, MENSAGENS_RESPONDER,
    PONTOS_VER, PONTOS_LANCAR,
    EQUIPE_VER, EQUIPE_CONVIDAR
}
