
ALTER TABLE TB_EVENTO_SAUDE ADD ds_status VARCHAR2(20) DEFAULT 'SOLICITADO' NOT NULL;
ALTER TABLE TB_EVENTO_SAUDE ADD ds_motivo_cancelamento VARCHAR2(300);

ALTER TABLE TB_EVENTO_SAUDE ADD CONSTRAINT ck_evento_status
    CHECK (ds_status IN ('SOLICITADO','CONFIRMADO','CONCLUIDO','CANCELADO'));