ALTER TABLE TB_PET_ACESSO DROP CONSTRAINT ck_acesso_permissao;
ALTER TABLE TB_PET_ACESSO ADD CONSTRAINT ck_acesso_permissao
    CHECK (ds_permissao IN ('LEITURA','EDICAO','VISUALIZAR_PERFIL','VISUALIZAR_AGENDA',
                            'VISUALIZAR_CARTEIRA','CRIAR_EVENTO','EDITAR_PERFIL'));
ALTER TABLE TB_PET_CONVITE DROP CONSTRAINT ck_convite_permissao;
ALTER TABLE TB_PET_CONVITE ADD CONSTRAINT ck_convite_permissao
    CHECK (ds_permissao IN ('LEITURA','EDICAO','VISUALIZAR_PERFIL','VISUALIZAR_AGENDA',
                            'VISUALIZAR_CARTEIRA','CRIAR_EVENTO','EDITAR_PERFIL'));
