ALTER TABLE TB_TUTOR ADD dt_senha_alterada_em TIMESTAMP(6) NULL;
ALTER TABLE TB_VETERINARIO ADD dt_senha_alterada_em TIMESTAMP(6) NULL;
ALTER TABLE TB_PROFISSIONAL_ESTETICA ADD dt_senha_alterada_em TIMESTAMP(6) NULL;
ALTER TABLE TB_ADMIN ADD dt_senha_alterada_em TIMESTAMP(6) NULL;
