
UPDATE TB_EVENTO_SAUDE
SET ds_status = 'AGENDADO'
WHERE ds_status IN ('SOLICITADO', 'CONFIRMADO');


ALTER TABLE TB_EVENTO_SAUDE DROP CONSTRAINT ck_evento_status;

ALTER TABLE TB_EVENTO_SAUDE ADD CONSTRAINT ck_evento_status
    CHECK (ds_status IN ('AGENDADO', 'CONCLUIDO', 'CANCELADO'));


ALTER TABLE TB_EVENTO_SAUDE MODIFY (ds_status DEFAULT 'AGENDADO');