
ALTER TABLE TB_PRESCRICAO ADD ds_status VARCHAR2(20) DEFAULT 'SOLICITADO' NOT NULL;

ALTER TABLE TB_PRESCRICAO ADD CONSTRAINT ck_prescricao_status
    CHECK (ds_status IN ('SOLICITADO', 'LIBERADO', 'NEGADO'));

ALTER TABLE TB_PRESCRICAO ADD id_admin_validador NUMBER;

ALTER TABLE TB_PRESCRICAO ADD CONSTRAINT fk_prescricao_admin_validador
    FOREIGN KEY (id_admin_validador) REFERENCES TB_ADMIN (id_admin);